services:
  - type: web
    name: benq-validator
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app -b 0.0.0.0:$PORT
    routes:
      - type: web
    healthCheckPath: /
